#version 430

layout(local_size_x = 16, local_size_y = 16) in;
layout ( rgbaf32, binding = 0 ) uniform image2D img_output;
layout(std430, binding = 0) buffer Models { mat4 modelMatrices[]; };
layout(std430, binding = 1) buffer InvModels { mat4 inverseModelMatrices[]; };
layout(std430, binding = 2) buffer Materials { vec4 materialData[]; };
layout(std430, binding = 3) buffer BVH { vec4 bvhNodes[]; };